server:
  port: 8081
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sgca
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update # ou "create" para gerar as tabelas automaticamente
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true



sgca:
  security:
    jwt:
      secret: ${JWT_SECRET:bG9uZy1yYW5kb20tc2VjdXJlLWtleS1mb3ItamF2YS1zdHJpbmctand0LWVuY29kaW5nLTQ2Nzg5MA==}
      expiration-minutes: 60

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
